// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsu53nYV9X3NkBVFWsgq-sYCHCe6NSj5A',
    appId: '1:457000743468:web:e0b2c97b012f720a569789',
    messagingSenderId: '457000743468',
    projectId: 'amman-bef7c',
    authDomain: 'amman-bef7c.firebaseapp.com',
    databaseURL: 'https://amman-bef7c-default-rtdb.firebaseio.com',
    storageBucket: 'amman-bef7c.appspot.com',
    measurementId: 'G-8WE1RNXTJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKlKuRQKsJ2fSJlbk1gohKaKeRZVVKafA',
    appId: '1:457000743468:android:2195586408781369569789',
    messagingSenderId: '457000743468',
    projectId: 'amman-bef7c',
    databaseURL: 'https://amman-bef7c-default-rtdb.firebaseio.com',
    storageBucket: 'amman-bef7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn2URMSLwK6EkekuVyPyXoDRX0MscTaAE',
    appId: '1:457000743468:ios:b0582395eb5d365d569789',
    messagingSenderId: '457000743468',
    projectId: 'amman-bef7c',
    databaseURL: 'https://amman-bef7c-default-rtdb.firebaseio.com',
    storageBucket: 'amman-bef7c.appspot.com',
    iosClientId: '457000743468-f9fgd7etcddhgpr05kisscgqd1ot03l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ammanbus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn2URMSLwK6EkekuVyPyXoDRX0MscTaAE',
    appId: '1:457000743468:ios:e0e428c72757b353569789',
    messagingSenderId: '457000743468',
    projectId: 'amman-bef7c',
    databaseURL: 'https://amman-bef7c-default-rtdb.firebaseio.com',
    storageBucket: 'amman-bef7c.appspot.com',
    iosClientId: '457000743468-i0j757ch2cc74ak4pa4tnsbkgjbkhd35.apps.googleusercontent.com',
    iosBundleId: 'com.example.ammanbus.RunnerTests',
  );
}
